### ISSUE TITLE
setVolume doesn't change the output level 

### ISSUE THREAD

**Issue by wautersj** [tessel/audio-vs1053b#39]
I'm setting the volume of the audio output, where I have earplugs plugged-in.
I'm setting it to 0.1 as number, but the thing still keeps playing sound at full volume.

I'm playing the sound in the callback handler.

```javascript
audio.setVolume(.1, function(err){
    if (err) {
      return console.log(err);
    }

    var sound = fs.readFileSync('mySound.mp3');
    audio.play(sound, function(err) {
    if (err) {
      console.log(err);
    }
  }
});
```

**Comment by Frijol** [comment]
closing based on @johnnyman727 not being able to replicate [here](https://forums.tessel.io/t/setting-output-volume/1512), please feel free to reopen if unresolved
